### ISSUE TITLE
anthy-corpus/corpus.4.txt の取り扱いについて

### ISSUE THREAD

**Issue by tkng** [akaza-im/akaza-default-model#9]
https://github.com/akaza-im/akaza-default-model/blob/main/anthy-corpus/corpus.4.txt

このファイルは誤変換が含まれているものなので、評価には使うべきではありません。
ただ、このファイルだけリポジトリから削除すると謎の欠番が残りますし、どう扱うのがベストなのかはよくわかりません…。

**Comment by tokuhirom** [comment]
おっと。誤変換のファイルを評価用に使ってはダメですね。。
無視するように設定します
